from sklearn.gaussian_process.kernels import DotProduct, RBF
from kooplearn.data import traj_to_contexts
from kooplearn.models import NystroemKernel
import numpy as np
import torch
import ot

class KernelDMD(NystroemKernel):
    def __init__(
            self,
            data,
            n_delays,
            kernel=RBF(),
            num_centers=0.1,
            delay_interval=1,
            rank=10,
            reduced_rank_reg=True,
            lamb=1e-10,
            verbose=False,
            svd_solver='arnoldi',
        ):
        """
        Subclass of kooplearn that uses a kernel to compute the DMD model.
        This will also use Reduced Rank Regression as opposed to Principal Component Regression (above).
        """
        super().__init__(kernel, reduced_rank_reg, rank, lamb, svd_solver, num_centers)
        self.n_delays = n_delays 
        self.context_window_len = n_delays + 1
        self.delay_interval = delay_interval
        self.verbose = verbose
        self.rank = rank
        self.lamb = 0 if lamb is None else lamb
        
        self.data = data

    def fit(
            self,
            data=None,
            lamb=None,
        ):
        """
        Fits the Kernel DMD model to the provided data.

        Parameters
        ----------
        data : np.ndarray or torch.tensor
            The data to fit the DMD model to. Defaults to None, using the initialized data.

        lamb : float
            Regularization parameter for ridge regression. Defaults to None, using the initialized value.
        """
        data = self.data if data is None else data
        lamb = self.lamb if lamb is None else lamb

        self.compute_hankel(data)
        self.compute_kernel_dmd(lamb)

    def compute_hankel(self, trajs):
        """
        Computes delay embeddings for the given trajectories.

        Parameters
        ----------
        trajs : np.ndarray or list
            Input trajectories for Hankel matrix computation.
        """
        if isinstance(trajs, torch.Tensor):
            trajs = trajs.numpy()
        if isinstance(trajs, np.ndarray) and trajs.ndim == 2:
            trajs = trajs[np.newaxis, :, :]

        data = traj_to_contexts(trajs[0], context_window_len=self.context_window_len,
                                time_lag=self.delay_interval)
        idx = np.zeros(data.idx_map.shape)
        data.idx_map = np.concatenate((idx, data.idx_map), axis=-1)
        for i in range(1, len(trajs)):
            new_traj = traj_to_contexts(trajs[i], context_window_len=self.context_window_len,
                                         time_lag=self.delay_interval)

            data.data = np.concatenate((data.data, new_traj.data), axis=0)

            idx = np.zeros(new_traj.idx_map.shape) + 1 
            new_traj.idx_map = np.concatenate((idx, new_traj.idx_map), axis=-1)
            data.idx_map = np.concatenate((data.idx_map, new_traj.idx_map), axis=0)

        self.data = data

        if self.verbose:
            print("Hankel matrix computed")

    def compute_kernel_dmd(self, lamb=None):
        """
        Computes the Kernel DMD model.
        """
        self.tikhonov_reg = self.lamb if lamb is None else lamb
        super().fit(self.data)
        self.A_v = self.V.T @ self.kernel_YX @ self.U / len(self.kernel_YX)

        if self.verbose:
            print("Kernel regression complete")

    def predict(self, test_data, reseed=None):
        """
        Predicts future trajectories using the Kernel DMD model.

        Parameters
        ----------
        test_data : np.ndarray
            Input test data for prediction.

        reseed : int or None
            Reseeding parameter (not implemented).

        Returns
        -------
        pred_data : np.ndarray
            Predictions generated by the Kernel DMD model.
        """
        if reseed is None:
            reseed = 1
        else:
            raise NotImplementedError
        
        if isinstance(test_data, torch.Tensor):
            test_data = test_data.numpy()
        if isinstance(test_data, list):
            test_data = np.array(test_data)

        isdim2 = test_data.ndim == 2
        if isdim2:
            test_data = test_data[np.newaxis, :, :]

        pred_data = np.zeros(test_data.shape)
        pred_data[:, 0:self.n_delays] = test_data[:, 0:self.n_delays]

        self.compute_hankel(test_data)

        pred = super().predict(self.data)
        pred = pred.reshape(test_data.shape[0], test_data.shape[1]-self.n_delays, test_data.shape[2])
        pred_data[:, self.n_delays:] = pred

        return pred_data